### ISSUE TITLE
Page Type and Multi Language

### ISSUE THREAD

**Issue by chibikun** [Lednerb/bilberry-hugo-theme#100]
Dear Lednerb, great theme, great multilanguage features now! Awesome , thanks!

I have now started to use the latest version but have an issue understanding multilingual implementation:

In the former single language version I created pages to have kind of a shortcut to specific content types that I created, means the top nav would have the content type as name and then the URL as parameter which worked fine. 

Now it also works fine but there is one slight issue: I always land at the same language.
I tried to implement three pages with different languages which didn't work out well.

Do you have any hint or is my arkward usage of the theme just not possible?

Thanks a lot again,

David

**Comment by Lednerb** [comment]
Hi David,
can you please provide a short snippet of your code changes?

Do you use the `relLangURL` function to create the links?

**Comment by chibikun** [comment]
Hi Sascha, 

no code changes done. Just missed out to use the relLangURL parameter instead of plain url in the page types front matter. 

Solved! Thanks a lot!!

David
