### ISSUE TITLE
Render incorrect task list

### ISSUE THREAD

**Issue by ihelwn** [Lednerb/bilberry-hugo-theme#108]
test.md file source
<img width="197" alt="screen shot 2018-08-31 at 18 40 58" src="https://user-images.githubusercontent.com/42862130/44905589-7877bc00-ad4d-11e8-99ce-d350dc1e4d45.png">

result screen
<img width="198" alt="screen shot 2018-08-31 at 18 41 09" src="https://user-images.githubusercontent.com/42862130/44905592-7ada1600-ad4d-11e8-9576-7ac5065189dc.png">

Task list item exists on new line

/ # hugo version
Hugo Static Site Generator v0.47 linux/amd64 BuildDate: 2018-08-17T09:15:20Z

theme version
[1.9.1] - 2018-08-30

plz check issue

thank you

**Comment by Lednerb** [comment]
Fixed it.  Check out the next release.
