### ISSUE TITLE
categories and tags page listings are blank (empty)

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#109]
I am testing the theme for the first time (which is great! good job).
I have added some posts but when I click on the category names and tags, this gives me a blank page.

I see in your demo https://lednerb.github.io/bilberry-hugo-theme/categories/ that this works! 

Did I miss something to get that working (any special configuration?)

Thanks

**Comment by Lednerb** [comment]
Hi, what version have you installed?

Is this configuration in your `config.toml` file?
https://github.com/Lednerb/bilberry-hugo-theme/blob/master/exampleSite/config.toml#L115

**Comment by Djas2017** [comment]
Hi,

Hugo version: v0.48

`$ hugo env
Hugo Static Site Generator v0.48/extended darwin/amd64 BuildDate: unknown
GOVERSION="go1.11"`

Yes, the configuration file is the one you have mentioned  https://github.com/Lednerb/bilberry-hugo-theme/blob/master/exampleSite/config.toml#L115
`# don't change anything below
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"`

**Comment by Lednerb** [comment]
Thanks,

I've just reinstalled the theme on my local machine and it's working without any problems.

Do you have different config files like `.yaml` and `.toml` side by side?

Did you follow the [Quick start](https://github.com/Lednerb/bilberry-hugo-theme#quick-start) instructions?

**Comment by Djas2017** [comment]
Thanks for the followup.
I will reinstall it again and provide feedback. May be I have missed something!

**Comment by Djas2017** [comment]
I have reinstalled again a created new blog following the instructions in the Quick start instructions and the categories & tags pages work well now.

**NEW BUG**: Let me know if you want me to open a new issue for this
I am facing another issue with the brand new blog is that the **Font Awesome Icons are not displayed**.

**QUESTION**:
Could we use **external images for the gallery sliders and article featured images** (I ant for example to have the images stored in AWS S3 or somewhere else, and .not in the same server where the blog is hosted).
