### ISSUE TITLE
Add a hint for the hugo extended version for sass support.

### ISSUE THREAD

**Issue by ihelwn** [Lednerb/bilberry-hugo-theme#111]
$ hugo server
Building sites … ERROR 2018/09/13 09:20:52 error: failed to transform resource: TOCSS: failed to transform "sass/theme.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 64 ms
Error: Error building site: logged 1 error(s)

$ hugo version
Hugo Static Site Generator v0.48 linux/amd64 BuildDate: 2018-08-29T06:33:51Z

please check issue

**Comment by Lednerb** [comment]
Hi @ihelwn you will need the extended version of hugo.

I have to add the hint to the README.md file.

Please download or install the extended version for this theme, you can find it here:
https://github.com/gohugoio/hugo/releases

**Comment by nnja** [comment]
The readme should also be modified to remove the outdated instructions for using `yarn`

**Comment by Lednerb** [comment]
Done by @nnja in #131 - THANKS!
