### ISSUE TITLE
404 on fonts

### ISSUE THREAD

**Issue by lingej** [Lednerb/bilberry-hugo-theme#114]
Local fonts are not found while running hugo server

latest working version ist 1.9.1

```
Request URL: http://localhost:1313/bilberry-hugo-theme/dist/fonts/open-sans-v15-vietnamese_latin_greek_cyrillic-ext_greek-ext_latin-ext_cyrillic-regular.woff2
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1313
Referrer Policy: no-referrer-when-downgrade
```

```
Request URL: http://localhost:1313/fonts/fontawesome-webfont.woff2?v=4.7.0
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1313
Referrer Policy: no-referrer-when-downgrade
```

**Comment by nnja** [comment]
Updated to the newest theme version today, and I'm experiencing the same issue

**Comment by nnja** [comment]
@lingej This issue was affecting me too, so I opened a PR. See https://github.com/Lednerb/bilberry-hugo-theme/pull/115/commits/edf40a76eaa25daf29a58df396115c945fbceae2

**Comment by Lednerb** [comment]
I've just released the hotfix version 1.11.1 that fixes the error by respecting the `.Site.BaseURL` parameter.

**Comment by lingej** [comment]
Hi @Lednerb 

my config.toml contains

baseURL = "/"
relativeurls = true

because my site is served on different domains

1.11.1 does not work with baseURL="/"

Joerg

**Comment by Lednerb** [comment]
Hi @lingej 

Can you give me an example of how your URLs look like?

Maybe a `fontsFolder` config can help you?

I'm just thinking about how to fix this in an elegant way but at the moment I've no good idea.


We have this in the `_variables.scss`:
```
$fonts-folder: '{{ .Site.BaseURL  }}/dist/fonts/';
```

so maybe we extend it as:

```
$fonts-folder: '{{ .Site.Params.FontFolder | default .Site.BaseURL + "dist/fonts/" }}';
```

What do you think?

**Comment by lingej** [comment]
Hi @Lednerb 

currently baseURL = "https://ederdrom.de"

See a working example https://ederdrom.de/
and the broken fonts on https://www.ederdrom.de/

Before 1.11.1 I just used baseURL = "/"

**Comment by Lednerb** [comment]
on https://www.ederdrom.de the `/dist/` part is missing.

I will push to `development` in just a minute, maybe you can test and tell me if the problem is solved.

**Comment by lingej** [comment]
baseURL = "/" results in $fonts-folder: '//dist/fonts/';

// results in https://dist/fonts

This is like an URI without Protocol Scheme

**Comment by Lednerb** [comment]
Please check out the actual `development` branch now.

The `.Site.BaseURL` needs a trailing slash at the moment.

If this does not work for you, you can add the `customFontsURL` to your `config.toml` to the `[params]` list.

**Comment by lingej** [comment]
works for me with baseURL="/"

just an other hint from hugo version 0.48/extended

```
Building sites … DEPRECATION WARNING on line 40, column 36 of stdin:
The value "#ffffff80" is currently parsed as a string, but it will be parsed as a color in
future versions of Sass. Use "unquote('#ffffff80')" to continue parsing it as a string.
```

https://github.com/Lednerb/bilberry-hugo-theme/blob/master/assets/sass/_variables.scss#L40

Thanks a lot !

Joerg
