### ISSUE TITLE
Question: Could we store the images used in Featured articles and Gallery sliders in an external server (AWS S3 or somewhere else)

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#120]
Could we use external images for the gallery sliders and article featured images (I ant for example to have the images stored in AWS S3 or somewhere else, and not in the same server where the blog is hosted).

In this example:
`ls content/gallery/my-trip-to-scotland/`
`index.de.md	index.md	scotland1.jpg	scotland2.jpg	scotland3.jpg	scotland4.jpg	scotland5.jpg`

I want the images scotland1.jpg, ..., scotland5.jpg to be stored in an external images storage server. These images will be accessed remotely like: https://www.image-server.tld/images/scotland1.jpg, ....

**Comment by Lednerb** [comment]
Hi,

yes, you can add an gallery array to your gallery post, like

```
gallery: [
"url1",
"url2",
...
]
```

Not checked yet but should work for external images.

This was the default behavior a while ago, we have to add this method to the README.md

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 17. Sep. 2018, 23:28, Djas2017 schrieb:

**Comment by Djas2017** [comment]
Great! I have tested it for gallery and this works! 

>>>>>>>> ??? Does the same logic works for an article (content/article/) to replace the local featuredImage.png with an external image? I have tried the keyword ""gallery, but it didn't work.

**Comment by Lednerb** [comment]
Nice!

You can add the keyword featuredImage: "URL" for the featured images.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 18. Sep. 2018, 05:54, Djas2017 schrieb:

**Comment by Djas2017** [comment]
> You can add the keyword featuredImage: "URL" for the featured images.
Tested and it is working. Thanks for your fast replies!
