### ISSUE TITLE
Error when building site on Ubuntu server failed to transform "sass/combined.scss" (text/x-scss)

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#122]
Trying to get the hugo bilberry-hugo-theme working on an Ubuntu server, but I got this error:
`Building sites … ERROR 2018/09/18 error: failed to transform resource: TOCSS: failed to transform "sass/combined.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 230 ms
Error: Error building site: logged 1 error(s)`

- Ubuntu version: 
`Ubuntu 16.04.5 LTS`
- hugo version: Latest from https://github.com/gohugoio/hugo/releases/ 
`Hugo Static Site Generator v0.48 linux/amd64 BuildDate: 2018-08-29T06:33:51Z`
- Theme: config.toml 
`theme = "bilberry-hugo-theme"`

PS: On MacOSX, everything works well! (I use Hugo Static Site Generator v0.48/extended darwin/amd64)

**Comment by Lednerb** [comment]
On Ubuntu you have to use the extended version, too.

It seems like it's the standard one?

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 18. Sep. 2018, 13:44, Djas2017 schrieb:

**Comment by Djas2017** [comment]
I will try the extended version and provide feedback

**Comment by Djas2017** [comment]
You are right! 
It works with the extended version from https://github.com/gohugoio/hugo/releases/ 

https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_extended_0.48_Linux-64bit.deb 

Thanks!

**Comment by Lednerb** [comment]
Thank you for the reply :)

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------
An 19. Sep. 2018, 18:40, Djas2017 schrieb:
