### ISSUE TITLE
Building sites … ERROR 

### ISSUE THREAD

**Issue by jamestagal** [Lednerb/bilberry-hugo-theme#129]
I have installed your Hugo theme today as a submodule and did the configuration step ie : copied the config.toml content over to the root config.toml file. Then when trying to run the server locally i got the following error message:

`Building sites … ERROR 2018/09/26 15:04:49 error: failed to transform resource: TOCSS: failed to transform "sass/combined.scss" (text/x-scss): this feature is not available in your current Hugo version.`

My Hugo version:
Hugo Static Site Generator  v0.48 windows/amd64 BuildDate: 2018-08-29T06:35:13Z

**UPDATE:** 
I was able to update my Hugo version via Chocolatey package manager on Windows today but am getting the same errors as per my post below that I got from my Mac. The one I installed was:
Hugo Static Site Generator v0.49 windows/amd64 BuildDate: 2018-09-24T10:01:53Z

**Comment by Lednerb** [comment]
Hello,

you have to use the extended hugo version that you can get from their offical release page. 

See #111

**Comment by jamestagal** [comment]
Hello,
I am using a Chocolatey package manager on Windows is has not been updated as far as I am aware.
https://discourse.gohugo.io/t/hugo-0-49-released/14375
Ben

**Comment by jamestagal** [comment]
Hi Lebnerb,
I tried on my Mac and installed the following Hugo version but got an error although it was a different error with this set up:

> Hugo Static Site Generator v0.49/extended darwin/amd64 BuildDate: unknown

`Building sites … ERROR 2018/09/29 23:38:41 Error while rendering "taxonomyTerm" in "": template: _default/list.html:58:59: executing "_default/list.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
ERROR 2018/09/29 23:38:41 Error while rendering "home" in "": template: index.html:58:59: executing "index.html" at <resources.Concat>: error calling Concat: slice []interface{} not supported in concat
ERROR 2018/09/29 23:38:41 Error while rendering "404" in "": template: 404.html:58:59: executing "404.html" at <resources.Concat>: error calling Concat: slice []interface {} not supported in concat
Total in 84 ms
Error: Error building site: logged 3 error(s)`

So I will just wait for your explorations into these issues.
Best regards,
Ben

**Comment by webratz** [comment]
I see that same issue while using the 0.49 extended deb package (hugo_extended_0.49_Linux-64bit.deb) on Ubuntu 18.04.

**Comment by szjani** [comment]
I have the same "Concat" issue on Windows. I have to use 1.9.1, newer versions cannot be built.

**Comment by Lednerb** [comment]
Related to #128 

Closing here and working for on a fix.

**Comment by jamestagal** [comment]
Hello @Lednerb 
i just tried this latest release and still get the original error I posted 
`Building sites … ERROR 2018/10/09 14:24:00 error: failed to transform resource: TOCSS: failed to transform "sass/combined.scss" (text/x-scss): this feature is not available in your current Hugo version`

Again my Hugo version is as follows:
Hugo Static Site Generator v0.49 windows/amd64 BuildDate: 2018-09-24T10:01:53Z

Cheers,
Ben
