### ISSUE TITLE
Are the h3 and h4 designs intended?

### ISSUE THREAD

**Issue by ihelwn** [Lednerb/bilberry-hugo-theme#142]
Hello, I'm using very well.
thank you for bilberry-hugo-theme developer

I have question

Are the h3 and h4 designs intended?

![image](https://user-images.githubusercontent.com/42862130/47342446-b73b4a00-d6de-11e8-88e4-28dad21c47e5.png)

![image](https://user-images.githubusercontent.com/42862130/47342416-a38fe380-d6de-11e8-8969-0e5f0cae590b.png)

and

{{< highlight javascript >}}
<script>
</script>
{{< /highlight >}}

result is 
![image](https://user-images.githubusercontent.com/42862130/47343161-75ab9e80-d6e0-11e8-9d15-5d939afb8e31.png)

Is Possible that the left [, right ] outer color change the white?

thank you

**Comment by Lednerb** [comment]
I have to check this, but the `{{<highlight ... >}}` shortcode is not configured for the hugo theme.

There is the usage of `highlight.js` to do this, maybe the issue is caused by this.

Just try to use the ``` syntax.

----

The `h3` and `h4` tags are not designed well, this has to be fixed.
