### ISSUE TITLE
Do you plan to add the Table of Contents feature?

### ISSUE THREAD

**Issue by ihelwn** [Lednerb/bilberry-hugo-theme#143]
I would like to have a function that automatically creates a table of contents for h1 ~ h6 items.

If there is a table of contents at the top of the article and you have the ability to jump to the head when you click on an item, you may be able to find the item you want faster.

**Comment by jeremejazz** [comment]
A configuration option could be good 
`toc = true`

**Comment by jeremejazz** [comment]
@ihelwn for the meantime though you can override a layout file like [default-content.html](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/default-content.html) the add the [shortcode](https://gohugo.io/content-management/toc/) by creating the file on your layout folder. More info from docs:
https://gohugo.io/templates/base/

I did something similar with [Hello Friend theme ](https://github.com/panr/hugo-theme-hello-friend/issues/68#issuecomment-503484672) hope it helps

**Comment by igor-baiborodine** [comment]
@Lednerb 
I will implement this feature and fix issue #252 at the same time.
