### ISSUE TITLE
Tag Bug

### ISSUE THREAD

**Issue by ihelwn** [Lednerb/bilberry-hugo-theme#144]
config.toml -> disablePathToLower = true

![image](https://user-images.githubusercontent.com/42862130/47614917-f73d6b00-daea-11e8-9c3e-d83c8caafb8d.png)
'JavaScript' Tag Click

![image](https://user-images.githubusercontent.com/42862130/47614920-08867780-daeb-11e8-8ef2-85907c4514e0.png)
http://localhost/tags/JavaScript/
404 page not found

but

http://localhost/tags/javascript/ <- lower 
![image](https://user-images.githubusercontent.com/42862130/47614934-34096200-daeb-11e8-945e-6a4cdf26a3d9.png)
Ok

thank you.

**Comment by Lednerb** [comment]
It seems like this is a general error with `disablePathToLower = true` because the article URLs don't get rendered with capitals either...

**Comment by Lednerb** [comment]
Fixed by 413f53c

See also: https://github.com/gohugoio/hugo/issues/6884
