### ISSUE TITLE
can not start server , TOCSS failed to transform sass/combined.scss 

### ISSUE THREAD

**Issue by changchichung** [Lednerb/bilberry-hugo-theme#145]
OS: ubuntu 18.04
hugo 0.50
```
chchang@hexo:~/hugo/bil$ hugo env
Hugo Static Site Generator v0.50 linux/amd64 BuildDate: 2018-10-29T09:52:34Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.11"
chchang@hexo:~/hugo/bil$ 
```

error when start hugo server
```
chchang@hexo:~/hugo/bil$ hugo server -D
Building sites … ERROR 2018/10/31 13:52:14 error: failed to transform resource: TOCSS: failed to transform "sass/combined.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 686 ms
Error: Error building site: logged 1 error(s)
chchang@hexo:~/hugo/bil$ 
```

and hugo V0.46
```
chchang@hexo:~/hugo/bil$ hugo env
Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-01T09:00:55Z
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.10.1"
chchang@hexo:~/hugo/bil$ hugo server -D
Building sites … ERROR 2018/10/31 13:56:19 error: failed to transform resource: TOCSS: failed to transform "sass/combined.scss" (text/x-scss): this feature is not available in your current Hugo version
Total in 322 ms
Error: Error building site: logged 1 error(s)
chchang@hexo:~/hugo/bil$ 
```
I fetch hugo deb file from https://github.com/gohugoio/hugo/releases
any suggestions ??

**Comment by changchichung** [comment]
the install from gohugo just said apt-get install hugo , that`s version 0.40 , maybe you should update readme to use hugo_extended_0.xx from  https://github.com/gohugoio/hugo/releases

**Comment by Lednerb** [comment]
Already done ;)

https://github.com/Lednerb/bilberry-hugo-theme#requirements

**Comment by changchichung** [comment]
that`s the first documents I try to follow , but in that link 
https://gohugo.io/getting-started/installing/
search for Ubuntu , just said 
```
apt-get install hugo
```
but this only install hugo v0.40  , did not match the requirements.

**Comment by Lednerb** [comment]
That's right, but I'm not an official hugo maintainer and this theme is an open source contribution, not related to the main hugo project.

Hope you're doing well an can run the theme with the extended hugo version.
