### ISSUE TITLE
Question : Archive functionality

### ISSUE THREAD

**Issue by mandarvaze** [Lednerb/bilberry-hugo-theme#147]
Is there a plan to provide "archive" functionality where **all** posts are listed year/month wise ?

If it is already possible - how to achieve it ?

**Comment by Lednerb** [comment]
Until now there was no plan to do so, but I think this would be a nice feature.

----------

**Feature description**
Maybe you can enable it via the config file and get a link in the footer, called "Archive".
Clicking there will list all posts, sorted by date, grouped by month and year with a nice view for the used `tags` and `categories`.

**Comment by mandarvaze** [comment]
Since you have tagged it as "Help Wanted", I want to volunteer. 
But I have no experience working with hugo/themes.

If you provide some pointers, I may be able to dabble and provide some PR (or more questions)

**Comment by jamesrwaugh** [comment]
Seconding. The Lingonberry theme has a nice archive feature here, for example: https://andersnoren.se/themes/lingonberry/templates/archive-template/

**Comment by TeknikalDomain** [comment]
Seeing as this is still an open issue and there doesn't seem to be any relevant changes recently, I think I'll throw my hat into the ring.

**Comment by Lednerb** [comment]
@TeknikalDomain I'm open for PRs :)

**Comment by igor-baiborodine** [comment]
Resolved with PR https://github.com/Lednerb/bilberry-hugo-theme/pull/305
