### ISSUE TITLE
Taxonomy pages does not show.

### ISSUE THREAD

**Issue by phucduong86** [Lednerb/bilberry-hugo-theme#151]

**Comment by Lednerb** [comment]
Sorry for the long delay @phucduong86 ,

is this still an issue or did you found a solution already?

**Comment by phucduong86** [comment]
Hi @Lednerb,

Thanks for responding. Still blank taxonomy pages when I develop locally but it seems fine when I deploy to live.
It's not a big issue since my page still works.

**Comment by Lednerb** [comment]
Latest version tested today works as expected.

I've just checked your repo out and found the issue:

In your `config.toml` you have to set `uglyURLs = false` or remove it entirely.

I don't know exactly why this happens, but the solution will work for you.

BTW: I've updated the theme a lot today and released Version 1.14.0 while Version 2 is on the road!

**Comment by phucduong86** [comment]
Fantastic thank you.
