### ISSUE TITLE
How to keep the human readable names of images instead of the hashed names?

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#153]
Hi,

1) After generating the html version of the blog, in the public folder, all image names are replaced with a kind of hashes like:"_hu84e2839491c1e00....2507045_125438_2091538...f591dc4f36e7....656.png"

Is there any option in the config file to keep the original images naming? (For SEO)

2) Another question, what is the easiest and correct way to add image "alt" tag to the images included in the gallery posts. (For SEO)

Thanks

**Comment by Lednerb** [comment]
Hello @Djas2017 and sorry for the delay.

1. I can't verify the problem at the moment. How do you include the images? What kind of images are affected (gallery, featuredImage?)

2. At the moment there is no such option to set the alt tags.
A possible way would be to enhance the gallery function for [External Images](https://github.com/Lednerb/bilberry-hugo-theme#external-images), so you can define an array with `url` and `alt` attribute, but this is not planned by myself for the moment.

If you want, you can submit a PR for this functionality or open an Issue as a feature request, so maybe someone will implement this.

**Comment by Djas2017** [comment]
For the image names,  I have turned the resizeImages parameter to off and the image names now appear correctly. 
` # let hugo automatically resize and crop your images to the correct sizes
    resizeImages = false`

When it was turned on, it creates new images even if my original images are 750x350 

So we can consider this as closed. 

Thanks

**Comment by Lednerb** [comment]
We should add this to the documentation in the `README.md`.
