### ISSUE TITLE
Remove static pages from RSS feed

### ISSUE THREAD

**Issue by anoff** [Lednerb/bilberry-hugo-theme#159]
Is there a way to get an RSS feed link that includes all `content` instead of the article/code/xyz specific urls?

**Comment by anoff** [comment]
nevermind.. seems the root has this, only thing I would like to change is remove the "static" `page` from the RSS

**Comment by Lednerb** [comment]
Hey @anoff ,

I've reopened the issue because this would be a nice improvement for the theme!

Maybe you can send an PR with your changes to archive this?

Best regards and thank you for your other contributions as well!
