### ISSUE TITLE
Feature Request: HighlightJS Theme as config option

### ISSUE THREAD

**Issue by WardsParadox** [Lednerb/bilberry-hugo-theme#165]
Would it be possible to have the hightlightJS theme as a config option?
I'm trying to change the zenburn theme to the lightfair theme instead, but I don't see an easy way unless I fork the repo or modify the `assets/css/imports` file.

**Comment by WardsParadox** [comment]
Realized I could do this with a css_modules import of the highlight theme I wanted.

**Comment by Lednerb** [comment]
Thank you for your contribution! 

Nice, that this workaround works for you :+1:
