### ISSUE TITLE
Preview image on twitter not working

### ISSUE THREAD

**Issue by anoff** [Lednerb/bilberry-hugo-theme#168]
When adding a `featuredImage` to spice up the post overview page I create images with a large W:H ratio according to #44 . On slack the image is shown but on twitter it just shows a blank card.

slack:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/7142618/54868094-f7375380-4d88-11e9-9948-25d196f81fa9.png">

twitter:
![image](https://user-images.githubusercontent.com/7142618/54868101-01f1e880-4d89-11e9-889b-ce06bc440a40.png)

Is there another attribute that needs to be set for twitter or is the image just too wide?

**Comment by Lednerb** [comment]
Maybe @nisargap has more information on this?

See also: https://github.com/Lednerb/bilberry-hugo-theme/pull/82

**Comment by Lednerb** [comment]
Hey @anoff 

this should be fixed in the latest version in the `master` branch now.

![grafik](https://user-images.githubusercontent.com/2056876/88578399-c801b800-d048-11ea-8f73-915f3dcc25d0.png)

![grafik](https://user-images.githubusercontent.com/2056876/88578488-eebfee80-d048-11ea-8cda-a068f0bc6ece.png)


Feel free to open the issue again if you find another bug related to it.

**Comment by Sp-cy** [comment]
This issue hasn't been fixed. Twitter is extracting what it can from the OpenGraph values but it's lacking proper twitter card support. Here is the <head> tag in your same link. There is none twitter card values. 
![image](https://user-images.githubusercontent.com/68587155/114378369-40fc5d80-9b4d-11eb-81b4-460b5ff55224.png)

A page with twitter cards implemented would look like this: 
![image](https://user-images.githubusercontent.com/68587155/114378554-730dbf80-9b4d-11eb-819e-9e0ffb03fd78.png)


Would you like me to open a feature request for it? @Lednerb 

The twitter card partial in the theme i had seen before and couldn't really make it work myself either, I wanted the player card for my live streams but could never got it to work. I'm just a noob in web dev for now. Someone more experienced should be able to fix this in minutes.
