### ISSUE TITLE
googleAnalytics parameter in the config file does not seem to work

### ISSUE THREAD

**Issue by Djas2017** [Lednerb/bilberry-hugo-theme#169]
Hi,

I have added to the config.toml file:

googleAnalytics = "****My Tracking ID ***"

after building the blog, the google tracking code was not added to the html blog pages generated in the public folder.

Am I missing something here?

**Comment by Lednerb** [comment]
Maybe the theme does not include the standard analytics snippet.

I will put this on my todo list, but at the moment it will need a while until I can check this.

**Comment by Lednerb** [comment]
Just tested it again, after adding `googleAnalytics = "MY-TRACKING-ID"`  to the `config.toml` file, the following script block will appear in the rendered html:

```
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'MY-TRACKING-ID', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
```
