### ISSUE TITLE
Error paginator

### ISSUE THREAD

**Issue by sebastienhouzet** [Lednerb/bilberry-hugo-theme#172]
Hello

I have an error during 

hugo server -D

ERROR 2019/04/24 13:42:49 render of "home" failed: execute of template failed: template: 
index.html:19:7: executing "main" at <partial "paginator" .>: error calling partial: "/Users/XX/Git/XX/themes/bilberry-hugo-theme/layouts/partials/paginator.html:8:34": execute of template failed: template: partials/paginator.html:8:34: executing "partials/paginator.html" at <.Paginator.Prev.Permalink>: can't evaluate field Permalink in type *page.Pager
Total in 121 ms

I user lastest version of hugo 55.3 and theme on master.

Do you have an idea how to fix it ?

Thx

**Comment by lingej** [comment]
Same here!

change .Paginator.Prev.Permalink to .Paginator.Prev.URL

just a workaround because .URL is deprecated

Jörg

**Comment by mandarvaze** [comment]
@sebastienhouzet This should not be closed without the fix. I'm also getting this. Luckily, I looked thru the "closed" issues.
(cc @Lednerb )

**Comment by mandarvaze** [comment]
@Lednerb I think this needs a better fix. My PR will make the "error" go away, but as @lingej suggested, this is just a "workaround"

I found some discussion related to this [here](https://discourse.gohugo.io/t/url-warning/18385/2) - which clearly says that `URL is deprecated`

**Comment by Lednerb** [comment]
Thanks for the hint!

**Comment by Lednerb** [comment]
In the latest version 1.14.0 I don't have any issues, warning or error messages with hugo version 0.57/extended or 0.64/extended.

I will close here, if this issue occurs again, feel free to re-open it with further information.
