### ISSUE TITLE
Is favicon param used?

### ISSUE THREAD

**Issue by oika** [Lednerb/bilberry-hugo-theme#174]
In config.toml, there's a favicon param.

```
# Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon
```

This seems to be unused. Is it needed?

**Comment by Lednerb** [comment]
Thanks for the hint!

If this option is not used, it should be implemented.

**Comment by Lednerb** [comment]
It's not used.

To be able to set also the Icon for touch devices etc. there should be used a clear naming convention so the user only has to put the needed files within the `/static` folder.
