### ISSUE TITLE
IconFont requests are all 404.It seems that the font-folder config doesn't work

### ISSUE THREAD

**Issue by Oamha** [Lednerb/bilberry-hugo-theme#175]
`Request URL: http://localhost:1313/theme/bilberry-hugo-theme/dist/fonts/roboto-mono-v5
vietnamese_latin_greek_cyrillic-ext_greek-ext_latin-ext_cyrillic-regular.woff2
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1313
Referrer Policy: no-referrer-when-downgrade`
`Request URL: http://localhost:1313/theme/bilberry-hugo-theme/dist/fonts/fontawesome-webfont.woff?v=4.7.0
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:1313
Referrer Policy: no-referrer-when-downgrade`

**Do i need additional modification to the variables.scss file? Thank you.**

**Comment by Lednerb** [comment]
Hi,

sorry for the late response. I will check this as soon as I have time for it.

It seems like there is something wrong with the paths.

If everything is correct, you don't need modifications in the `variables.scss` file.

**Comment by Burnett01** [comment]
Use hugo-extended and edit ``{{ $fonts := "dist/fonts/" | absURL }}`` in **variables.scss**

Problem solved.
