### ISSUE TITLE
relative path in font-family appears to call localhost:1313 rather than using /dist/font

### ISSUE THREAD

**Issue by jonasmit** [Lednerb/bilberry-hugo-theme#178]
When using the bilberry theme on Netlify with Hugo 0.56 I am getting errors that prevent fonts from loading.  The scss appears to generate links for localhost rather than path appropriate for server-side resource in /dist/font folder.

GET http://localhost:1313/dist/fonts/fontawesome-webfont.ttf?v=4.7.0 net::ERR_FAILED

Access to font at 'http://localhost:1313/dist/fonts/comfortaa-v12-vietnamese_latin_greek_cyrillic-ext_latin-ext_cyrillic-regular.ttf' from origin 'https://sonsofatherton.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by an-t-oine** [comment]
i had the same behaviour.
To fixed it quickly by replacing all **localhost:1313** by my FQDN of my blog (**blog.mydomain.com**)
then, restart Nginx.
That's all.

**Comment by borco** [comment]
I had the same behaviour when using gitlab ci to deploy on gitlab pages.

The only step I had to do to fix this was to force gitlab to use the extended hugo docker image:

```
image: registry.gitlab.com/pages/hugo/hugo_extended:latest
```

This might actually not be a bug.

**Comment by Lednerb** [comment]
I will close this now.

Version 2 of this theme is in the pipeline.

If someone have the same issue, pls feel free to re-open it with further details.
