### ISSUE TITLE
Unable to update externalDependencies.js from imports file

### ISSUE THREAD

**Issue by motobreath** [Lednerb/bilberry-hugo-theme#180]
I see imports file points to Cloudflare hosted dependencies, and then externalDependencies.js is a single file aggregated from Cloudflare. I need to update to the latest version of Jquery, but updating imports file does not reflect the changes. 

How to update externalDependencies.js

**Comment by Lednerb** [comment]
At the moment it's implemented this way:

https://github.com/Lednerb/bilberry-hugo-theme/tree/master/assets/js

You should put all dependency-urls into the `imports` file.
Then you can run the command from the readme after `cd` into the folder:

```
wget -O externalDependencies.js -i imports
```

**Comment by Lednerb** [comment]
Short update:

I'm currently working on another method for dependency managament (using laravel-mix and npm instead of the previous way).

**Comment by Lednerb** [comment]
Sorry for the circumstances and delays.

In version 2 of this theme, that's now in the pipeline, the dependency management is done by `npm` and `laravel-mix`.

See the latest changes from 0197b17 for further information.
