### ISSUE TITLE
Kudos: I Used Your Theme!

### ISSUE THREAD

**Issue by Mike-EEE** [Lednerb/bilberry-hugo-theme#183]
A quick note of appreciation here for your theme.  I utilized it as a starting point and made my own customizations here:

https://blog.dragonspark.us/

Thank you for making it!

**Comment by Mike-EEE** [comment]
Going to close this now as it's more praise than an issue/bug. 😁

**Comment by Lednerb** [comment]
Hey @Mike-EEE !

Thank you very much for your message - I appreciate it very much!

Nice work with the pages menu!


Hopefully I will find some time for the open issues in the next days and maybe (but not very likely) I can start my own blog I've created this theme for :smile:
