### ISSUE TITLE
Potential bug: Posts not submitted in index.json for Algolia

### ISSUE THREAD

**Issue by TeknikalDomain** [Lednerb/bilberry-hugo-theme#188]
According to my current understanding of `layouts/index.json`, records are generated for tags, categories, and authors.

I think it would be nice if there was an option to enable generation of per-post records, maybe with a note indicating the potential cost (max records limit). Alternatively, a front matter variable could be added to override this on a per-page basis, to either only index some pages, or to manually exclude others.

Pull request(s) coming soon when I have enough free time to myself to attempt to work it through :sweat_smile:

**Comment by TeknikalDomain** [comment]
Actually, looking through the code, it looks like this might have been intended behavior.

**Comment by Lednerb** [comment]
Hey again @TeknikalDomain !

Thx for your contribution and the PR!
