### ISSUE TITLE
Unreadable syntax highlighting with plain / fallback languages

### ISSUE THREAD

**Issue by TeknikalDomain** [Lednerb/bilberry-hugo-theme#190]
The default syntax highlight with the theme appears to suffer from one major flaw: When the language is one of "plain", "text", "plaintext", or "fallback", the resulting styling rules will generate white text on what appears to be the site `background-color` background, meaning it's an unreadable combination of white text on a slightly off-white background.

When this happens, `theme.js` emits a warning that it's falling back to `no-highlight`, and "`Could not find the language 'plain', did you forget to load/include a language module?`" (`plain` replaced with appropriate language). This appears to be caused from `highlight.js`.

**Comment by Lednerb** [comment]
Hey, thanks for your feedback.

However, I cannot reproduce it.
Please tell me, how you markup your `plaintext` code.

See attached my test with the latest `master` version of this theme:
![screenshot_1](https://user-images.githubusercontent.com/2056876/74985139-2a6de100-5437-11ea-9c36-9746284a53e8.png)

**Comment by TeknikalDomain** [comment]
![Screenshot from 2020-02-20 17-34-48](https://user-images.githubusercontent.com/17773093/74986801-cc75d500-5407-11ea-9ec0-dd8673751944.png)
![Screenshot from 2020-02-20 17-35-19](https://user-images.githubusercontent.com/17773093/74986735-a8b28f00-5407-11ea-8ba6-b459d40852c3.png)

I'm on the previous commit before my PR merge, so the theme file shouldn't have been touched by that... there *might* be a few things on my end I'll have to reconfirm.

**Comment by TeknikalDomain** [comment]
The only potential issue I could see, which in fairness, might be completely my fault, is if I used a bad version of `highlight.js` when building a slightly tweaked theme bundle with changes to `_variables.scss`

`npm info highlight.js | grep version` reports `9.18.1`

If this is the case, then swapping back to normal would fix it and prove it's my end.

**Comment by Lednerb** [comment]
I think there's a bit of both involved:

1. According to `highlight.js` there is only `plaintext` available, `plain` is unknown so the `fallback` language style will used

2. The fallback language style is readable on the latest `master` commit, as you can see in the screenshot below, so maybe that's a fault on your side.

![screenshot_2](https://user-images.githubusercontent.com/2056876/75096314-cbc37700-559e-11ea-9851-5c22728a9c8f.png)

Please check an tell me if the same error occurs using the `plaintext` code formatting.

**Comment by TeknikalDomain** [comment]
`plaintext` does indeed... work as intended, I swear it gave the same error as before

Knowing me, I likely typed `paintext` by mistake and never noticed. One issue resolved at least.
Sorry about that.

**Comment by Lednerb** [comment]
You're welcome!
