### ISSUE TITLE
Algolia Search - "Nothing found"

### ISSUE THREAD

**Issue by tvories** [Lednerb/bilberry-hugo-theme#191]
Using Release 1.14.0

I have followed the instructions and set up Algolia for my site.  I have pasted the contents of index.json into my index at Algolia.  When I try to search my site I get "Nothing found" in the search box.
![image](https://user-images.githubusercontent.com/13934524/75264766-20d4d800-57ad-11ea-9c4d-eefd3e0c361a.png)

In Algolia I am able to "browse" my records and the search there works great.
![image](https://user-images.githubusercontent.com/13934524/75264715-0dc20800-57ad-11ea-944d-64460020897a.png)

Am I missing something?

**Comment by TeknikalDomain** [comment]
Just to verify here, the app ID, API key, and index name are all configured in `config.toml`, yes?

**Comment by tvories** [comment]
Correct, the settings are set correctly in my `config.toml`.

I can actually see the API calls coming into the application so I know the api keys are set correctly:
![image](https://user-images.githubusercontent.com/13934524/75370870-0a00b500-5883-11ea-979d-c05e8ec0f079.png)

I just get zero results.

**Comment by igor-baiborodine** [comment]
Hi,

Any progress on this issue? I have the same problem.

**Comment by tvories** [comment]
I have not been able to get it to work for me yet.

**Comment by Lednerb** [comment]
Thanks for looking into it @igor-baiborodine 
The updated docs are merged into `master` and are available on the README
https://github.com/Lednerb/bilberry-hugo-theme#algolia-search

I will close this now, if any issues still occur, feel free to re-open.

**Comment by tvories** [comment]
So deleting my index and re-building it according to the new instructions does give me results, but it does not appear to be returning matches for the titles of my articles or tags.

For example, I have a title with the word Ansible in it.  If I type Ansible, I get no results.  The only results I get are the non-article pages on my site.

![algolia](https://user-images.githubusercontent.com/13934524/83210695-c08d6380-a118-11ea-93c3-a8d20710f0d2.gif)

**Comment by igor-baiborodine** [comment]
Hi Taylor,

I would be happy to investigate this issue in my local dev, but I don't see your website's repo is present in your GitHub account. Therefore, if you provide me with a repo zip, I will work on it.

Thanks,

Igor

**Comment by igor-baiborodine** [comment]
Hi Taylor,

This issue comes from that you use tag 1.14.0. You can compare index.json files produced by the [master](https://github.com/igor-baiborodine/test-algolia/blob/master/public/index.json) branch and tag [1.14.0](https://github.com/igor-baiborodine/test-algolia/blob/tag-1.14.0/public/index.json).

You can clone this example site [repo](https://github.com/igor-baiborodine/test-algolia) and test it in your local dev. There are two branches: master and tag-1.14.0. If you switch to the branch **tag-1.14.0**, you will get the same search behavior as you currently have with your personal website. 

I hope this helps you.

Cheers,

Igor

**Comment by tvories** [comment]
@igor-baiborodine that fixed it!  I used the master branch and was able to uplaod the latest `index.json` and the results are good now!

I was running 1.14.0 because it allowed me to set the site width without editing the sass/scss but it wasn't difficult to get npm running to fix that issue.  Thanks for the help!
