### ISSUE TITLE
No umlauts possible in taxonomies

### ISSUE THREAD

**Issue by nidomiro** [Lednerb/bilberry-hugo-theme#196]
If a (article-)author is defined like `author: "a A"` everything works as expected.

But an author defined like `author: "a Aß"` or `author: "a Aä"` will result in a blank author.

I think the error happens in `/layouts/partials/default-content.html` between line 28 and 30.

Some Playing with values in line 28:
```
{{$.Site.GetPage (printf "/author/a-aß")}}
{{.}}
{{. | urlize}}
{{$.Site.GetPage (printf "/author/%s" ( . | urlize))}} 
```
Prints:
```
Page(/author/a-aß/_index.adoc)
a aß
a-a%C3%9
nopPage
```

**Comment by nidomiro** [comment]
My Quickfix is to replace 
```
{{ with $.Site.GetPage (printf "/author/%s" ( . | urlize)) }}
            <a href="{{ .Permalink }}">{{ .Title }}</a>
{{ end }}
```
with 
```
<a href="{{ ($.Site.GetPage (printf "/author/%s" ( replace ( lower . ) " " "-"))).Permalink }}">{{ . }}</a>
```

I hope there is a better version, mine is very hacky.

**Comment by Lednerb** [comment]
Hey @nidomiro 

Thx for opening this issue.

Due to the lack of spare time it might take a while until I can check this further.

I've shorly verified the bug and it seems that also other areas are affected.

**The same bug occurs on categories and tags.**

**Comment by nidomiro** [comment]
https://gohugo.io/functions/anchorize/ looks like the solution ;)

**Comment by nidomiro** [comment]
Ok, the game has not finished yet, anchorize has problems with + therefore "C++" will be "c"...

**Comment by nidomiro** [comment]
It's fixed now :)
https://github.com/Lednerb/bilberry-hugo-theme/pull/199#issuecomment-631462782
