### ISSUE TITLE
Algolia search icon disappear

### ISSUE THREAD

**Issue by enmanuelmoreira** [Lednerb/bilberry-hugo-theme#232]
Hi, 

I updated my website (itsimplenow.com) at the latest version of the bilberry theme, and the icon of algolia search disappear

![Screenshot from 2020-08-01 14-16-26](https://user-images.githubusercontent.com/152518/89107816-abc39980-d401-11ea-9cfa-91f6dd83eb1b.png)

Regards.

**Comment by Lednerb** [comment]
Fixed now.
