### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Lednerb** [Lednerb/bilberry-hugo-theme#24]
I want to implement the support for 2 or more different languages so you can write your post in DE, EN, RU, whatever and get a language chooser for this specific post.

Advantage:
- you don't have to translate all of your posts
- you can write some posts in your mother language and maybe in English to share the article with the whole world
- thanks to the i18n support the website should be translated correctly

**Comment by Dehong1** [comment]
If it includes Chinese,that will be great!

**Comment by Lednerb** [comment]
@Dehong1 
I will implement in a way, that every language can be used with the theme.

However, the theme would need a Chinese translation file for the static text.

Maybe you can submit a Chinese translation file for the `i18n` folder?

**Comment by aerohub** [comment]
It would be great to make error 404 article text customizable within either config or translation files.

**Comment by Lednerb** [comment]
See #46 for the 404 site.

**Comment by Lednerb** [comment]
In the next days the version 2.0.0 will be published :tada: 

I'm actually working on it, 80% is done.

@Dehong1 if you want to contribute a Chinese translation, feel free to submit them either here or per PR in as the other translation files like:

https://github.com/Lednerb/bilberry-hugo-theme/tree/feature-multiLangSupport-%2324/i18n
