### ISSUE TITLE
Youtube frame not responsive 

### ISSUE THREAD

**Issue by Aldhanekaa** [Lednerb/bilberry-hugo-theme#251]
hmm, I have tried if I add youtube frames to our blog, it won't be responsible for phone or desktop.
I mean if we add this, it won't responsive: 
<figure class="video_container">
  <iframe src="https://www.youtube.com/embed/youtubeID" frameborder="0" allowfullscreen="false"> </iframe>
</figure>

**Comment by Lednerb** [comment]
To be clear:

You want to add the `iframe` tag directly into the content area and are not (only) using the `video` post type to include the video to your article?

**Comment by Aldhanekaa** [comment]
> To be clear:
> 
> You want to add the `iframe` tag directly into the content area and are not (only) using the `video` post type to include the video to your article?

Yeah, I mean that

**Comment by Aldhanekaa** [comment]
> To be clear:
> 
> You want to add the `iframe` tag directly into the content area and are not (only) using the `video` post type to include the video to your article?

Yeah, actually, I didn't use video post type, I just add the iFrame tag to the article type.
I use it like this:
---
# front frame article post
---

<figure class="video_container">
  <iframe src="https://www.youtube.com/embed/enMumwvLAug" frameborder="0" allowfullscreen="true"> </iframe>
</figure>

**Comment by Lednerb** [comment]
Should be fixed by #262 

Please update your theme with the latest one from the `master` branch and checkout the updated docs:
https://github.com/Lednerb/bilberry-hugo-theme#Videos

Thanks to @igor-baiborodine
