### ISSUE TITLE
Title is emtpy for indexed page with the status type

### ISSUE THREAD

**Issue by igor-baiborodine** [Lednerb/bilberry-hugo-theme#253]
Shouldn't be a page excluded from indexing when its type is status? Since such pages have no titles by default, the search results are displayed as empty rows that are still clickable.

https://kiroule.com

![algolia-search-status-posts](https://user-images.githubusercontent.com/1027701/92819883-46b37a00-f397-11ea-8749-24814654edcc.gif)

**Comment by Lednerb** [comment]
Hey @igor-baiborodine 

you're right, the `status` post type should not be indexed for the search feature.

**Comment by igor-baiborodine** [comment]
@Lednerb 
Ok, I will fix it.
