### ISSUE TITLE
Header overlapping

### ISSUE THREAD

**Issue by gio-remo** [Lednerb/bilberry-hugo-theme#256]
First of all, my compliments for your work.

I noticed that in the header, with long title/subtitles, the toggler and the language chooser overlap over them.

I leave you an example. How could it be solved? 🤔
Thanks in advance :)

![example](https://user-images.githubusercontent.com/45832157/93318756-5c012c00-f80f-11ea-94a7-8d3ed1b40453.jpg)

**Comment by igor-baiborodine** [comment]
Fixed in PR https://github.com/Lednerb/bilberry-hugo-theme/pull/595.
