### ISSUE TITLE
Lost dependencies

### ISSUE THREAD

**Issue by uPagge** [Lednerb/bilberry-hugo-theme#268]
Hi

Where can you find these files?

![изображение](https://user-images.githubusercontent.com/40397740/105471327-aa39a680-5cab-11eb-8489-57b8ea589ae6.png)

**Comment by Lednerb** [comment]
You have to `npm install` the dependencies if you want to modify the CSS.

Further information:
https://github.com/Lednerb/bilberry-hugo-theme#Custom-colors-and-fonts

**Comment by uPagge** [comment]
thank you
