### ISSUE TITLE
Gellery

### ISSUE THREAD

**Issue by uPagge** [Lednerb/bilberry-hugo-theme#269]
![изображение](https://user-images.githubusercontent.com/40397740/106468954-a7129780-64af-11eb-9218-a2fb744b2b49.png)

I beg your pardon, I'm not good at hugo.

Therefore, I don’t understand in what case we fall into the last condition.

**Comment by Lednerb** [comment]
The last condition (Line 29) will be used if you create an article with the  `gallery` post type and set `imageSlider: false` in the article's frontmatter configuration.

**Comment by uPagge** [comment]
thank
