### ISSUE TITLE
[Feature] Custom audio file support

### ISSUE THREAD

**Issue by uPagge** [Lednerb/bilberry-hugo-theme#270]
I wanted to ask another question.

Here you can add your video, your file. And you can also add audio, file?

**Comment by Lednerb** [comment]
At the moment there is no custom audio implementation.

The [`audio` post type](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/content-type/audio.html) has to be rewritten like the [`video` post type](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/content-type/video.html) was done with the help of the [`video-embed.html` partial](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/video-embed.html)

**Comment by igor-baiborodine** [comment]
Closed with PR https://github.com/Lednerb/bilberry-hugo-theme/pull/299
