### ISSUE TITLE
Make font change possible and document it in README.md

### ISSUE THREAD

**Issue by tivasyk** [Lednerb/bilberry-hugo-theme#28]
The font by default is beautiful, but lacks Cyrillic support. I tried to something different from Google Fonts, found at least 3 CSS files with font specification, nothing seems to work, I end up with the local DejaVu on my screen.

**Comment by Lednerb** [comment]
Related to #9

**Comment by Lednerb** [comment]
Hello, my friend!

As you can see I've implemented an easier customization and the corresponding documentation in the [README.md](https://github.com/Lednerb/bilberry-hugo-theme#custom-colors-and-fonts).

Please let me know if everything works fine for you.

If you have a bit free time, you can fork this repository, implement a Ukrainian language file in the `i18n` folder and send me a Pull Request ;-)

Best regards!
