### ISSUE TITLE
featuredImage for local images

### ISSUE THREAD

**Issue by Defite** [Lednerb/bilberry-hugo-theme#341]
Subj, not working.

My structure is as follows:

```
content
 -- link
    some-link.md
    some-featured-image.jpg
```

in `some-link.md` I have:

```
---
title: "Duckduckgo.com"
date: 2021-11-01T13:05:27+01:00

categories: ["Privacy"]
tags: ["search engine"]

# Set your external url
link: "https://duckduckgo.com"
featuredImage: "./some-featured-image.jpg"
---

A search engine that respects your privacy.

```

Bug: the image is not showing.

**Comment by igor-baiborodine** [comment]
@Defite, internal images should be stored in the `static` folder.

Please see this working example:
https://www.bilberry-sandbox.kiroule.com/link/
https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/blob/master/content/link/test-link-with-featured-image.md
https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/blob/master/static/img/content/link/duckduckgo-featured-image.png

**Comment by Defite** [comment]
Ah, ok, thanks!
