### ISSUE TITLE
No images or video (as in demo site) - except avatar image and rollover image

### ISSUE THREAD

**Issue by darrenaddy** [Lednerb/bilberry-hugo-theme#348]
Firstly, thank you for this wonderful theme. I love all of the example content that comes with it. I'm relatively new to Hugo (couple of months) and have experimented with a number of different themes to see how different people do things. THIS is the one I plan to deploy as my actual blog. 

I realize that you JUST updated to v3.0.0 so perhaps this is a bug in the new version?

Now to the issue:
I downloaded the CODE from GitHub, unzipped it, and put it in the themes folder of my local machine.
Copied everything in the exampleSite folder to the project site root folder (overwriting everything).
Then I made a few edits to the config.toml in the site root folder and started the server with
hugo server -D --verbose

The site is being served, as expected, on the localhost port. But my home page (source) does not have <img src HTML tags, so no images are showing. Similarly, the images or video are not showing on the single post pages. 

TL;DR: I think the .Type is not getting passed to the partials/article-wrapper.html and when I look in the front matter, it appears that the line that should have "type:" is missing.

For example the front matter on the "My Trip To Scotland" index.md looks like this:
`---
title: "My Trip to Scotland"
date: 2021-11-01T18:01:26+01:00

categories: ['Travelling', 'Holidays']
tags: ['Scotland', 'Glennfinnan Viaduct', 'Eilean Donan Castle']
author: "Lednerb"
---`

Your demo site source code (viewed from the browser) for the Trip to Scotland post, for example, looks like this:

` <div class="article-wrapper u-cf">	
        	
            <a class="bubble" href="https://lednerb.github.io/bilberry-hugo-theme/gallery/my-trip-to-scotland/">	
    <i class="fas fa-fw fa-camera"></i>	
</a>	
<article class="gallery">	
    	
        <div class="flexslider">	
            <ul class="slides">	
                	
                    	
                        <li><img src="/bilberry-hugo-theme/gallery/my-trip-to-scotland/scotland1_hu92019f4794a0544a3ad4410e554ad3af_67831_700x350_fill_q95_box_smart1.jpg" /></li>	
                    	
                        <li><img src="/bilberry-hugo-theme/gallery/my-trip-to-scotland/scotland2_hud2b2cd68da7f6388575395354a188425_35351_700x350_fill_q95_box_smart1.jpg" /></li>	
                    	
                        <li><img src="/bilberry-hugo-theme/gallery/my-trip-to-scotland/scotland3_hu85c54f52b5fe4dbca0189cd47269771e_50040_700x350_fill_q95_box_smart1.jpg" /></li>	
                    	
                        <li><img src="/bilberry-hugo-theme/gallery/my-trip-to-scotland/scotland4_hu1c4902c66176c948fd8516244d69cc1e_56034_700x350_fill_q95_box_smart1.jpg" /></li>	
                    	
                        <li><img src="/bilberry-hugo-theme/gallery/my-trip-to-scotland/scotland5_hu5ddc646a14d071d83d62e36cc9a8eba6_46028_700x350_fill_q95_box_smart1.jpg" /></li>	
                    	
                	
            </ul>	
        </div>

<div class="content">	
    `
Whereas mine looks like this:

`	    <div class="article-wrapper u-cf">
        
            <a class="bubble" href="http://localhost:52079/gallery/my-trip-to-scotland/">
    <i class="fas fa-fw fa-pencil-alt"></i>
</a>
<article class="default article">
   
<div class="content">`

Similarly, on the video post, your demo site code looks like this:
`	    <div class="article-wrapper u-cf">	
        	
            <a class="bubble" href="https://lednerb.github.io/bilberry-hugo-theme/video/kilez-more-leben-und-tod-des-imperialismus/">	
    <i class="fas fa-fw fa-video"></i>	
</a>	
<article class="video">	
    	
    	
        	
    <div class="responsive-video youtube">	
        <iframe class="no-js-hidden" src="https://www.youtube-nocookie.com/embed/M7IjJiZUutk?rel=0" frameborder="0" allowfullscreen></iframe>	
        <div class="no-js-message">	
            The YouTube player can not be loaded with disabled JavaScript. <br>	
            The following video is embedded here: <br>	
            <a href="https://youtube.com/watch?v=M7IjJiZUutk" target="_blank">	
                https://youtube.com/watch?v=M7IjJiZUutk	
            </a>	
        </div>	
    </div>	
    	
    	
    	
    	
    	
    	
    <div class="content">`

Whereas mine looks like this:
`    <i class="fas fa-fw fa-pencil-alt"></i>
</a>
<article class="default article">
    
    <div class="content">`

Similarly, my music post is blank. Where yours begins with:
`<article class="audio">`

Mine begins with 
`	<article class="default article">`

In fact, all of my articles begin with class="default article" where yours are class=video or class=music or class=audio (for example).

Again, where your DuckDuckGo post is a class="link"
mine is a class="default article"
and
where your Snowden post is class="quote"
mine is again class="default article".

I'm going to try putting a type in the front matter to see if I'm right about the class part. But I'm not sure where you call the missing images or video from. Is that in the front matter of each post also?

Thanks for your help on this!

**Comment by igor-baiborodine** [comment]
@darrenaddy, Is it possible to publish your test website as a repository in your GitHub account? Then it will be easier for me to debug it in my local dev.

**Comment by igor-baiborodine** [comment]
I'm converting this issue into a discussion.
