### ISSUE TITLE
gallery breaks when theme directory is renamed

### ISSUE THREAD

**Issue by magiconair** [Lednerb/bilberry-hugo-theme#35]
When I import the theme as `bilberry` and not as `bilberry-hugo-theme` the `gallery` type does not render the images.

**Comment by Lednerb** [comment]
Hello, yeah this is a known issue at the moment...
I've hardcoded the directory name at some places for a more comfortable `content-type` check.

Have a look at #26.

We have three options:
1. We don't change the directory name (Why is this important for you?)
2. The Hugo developers provide the `theme` config as a `.Site` variable (unlikely to happen...)
3. We change the post type import routine and duplicate code.

At the moment I prefer option one while two would be my favorite.

**Comment by magiconair** [comment]
This isn't important to me but this is a hidden surprise which took me a while to figure out. I've followed the hugo tutorial which stripped the `-hugo-theme` suffix from the theme directory and that gave me the impression that the directory name doesn't matter. I didn't notice the warning you have in the README. Maybe you can move it into the code section as follows or make it more visible.

```
cd my-new-blog/themes

# do NOT change the directory name since otherwise the gallery will not show photos
git clone https://github.com/Lednerb/bilberry-hugo-theme.git
```

**Comment by Lednerb** [comment]
I've implemented the hint. 
THX for the suggestion!
