### ISSUE TITLE
Icons are not displayed when website is created using Bilberry theme as a Hugo module

### ISSUE THREAD

**Issue by igor-baiborodine** [Lednerb/bilberry-hugo-theme#354]
Icons are not displayed when a website is created using the Bilberry theme as a Hugo module. The same issue persists when an existing site is converted to Hugo modules.

1. Bilberry Sandbox converted to Hugo modules: https://deploy-preview-18--bilberry-sandbox.netlify.app/

2. New web site created in my local dev: 
![image](https://user-images.githubusercontent.com/1027701/154690562-f6bc9f50-f158-4cc4-959c-c3af9e47b1ea.png)

**Comment by igor-baiborodine** [comment]
When compared with deployment from master for the Bilberry Sandbox the `fonts/vendor` is missing:

![image](https://user-images.githubusercontent.com/1027701/154963909-0874e6d2-e32d-400a-8407-8dba286fef5f.png)

![image](https://user-images.githubusercontent.com/1027701/154963983-ebd739f1-1629-4e28-8a43-e06a7f4097b8.png)

**Comment by deining** [comment]
> When compared with deployment from master for the Bilberry Sandbox the `fonts/vendor` is missing:

This is due to a [known bug](https://github.com/golang/go/issues/37397) in go's module management. Unfortunately, this bug won't fix. I will check if I can come up with a fix here, I will have a look at this shortly.

**Comment by EvilOlaf** [comment]
I assume there is no other solution for this issue? The renaming did not do the trick for me :(

**Comment by EvilOlaf** [comment]
Not sure if I find time to do that but basically what I did was to rename the `/static/fonts/vendor/` folder to `/static/fonts/_vendor/` and used `sed` to replace all `vendor` with `_vendor` in `theme.css`. 

Would be nice if somebody could verify this as a fix.

**Comment by igor-baiborodine** [comment]
Closed with PR #394
