### ISSUE TITLE
Code with linenumbers is not displayed properly

### ISSUE THREAD

**Issue by nidomiro** [Lednerb/bilberry-hugo-theme#359]
If you use the following code in a post the result looks strange and highlighting lines does not work.

    ```rust {linenos=table,hl_lines=[3,"11-13"]}
    
    fn main() {
        println!("Please enter a calculation");
    
        let mut input = String::new();
    
        std::io::stdin()
            .read_line(&mut input)
            .expect("Could not read line");
    
        let parts: Vec<i32> = input.split(['+'])
            .map(|x| x.trim().parse().expect("Only numbers are allowed"))
            .collect();
    
        if parts.len() != 2 {
            panic!("Currently only + is a supported operator")
        }
    
    
        println!("Parts: {:?}", &parts);
    
        println!("{} + {} = {}", parts[0], parts[1], parts.iter().sum::<i32>())
    }
    
    
    ```

Result:

![image](https://user-images.githubusercontent.com/15079172/155685864-23d72bb1-02d2-4af4-b068-9f22e4024cb2.png)

The hugo feature is described here: https://gohugo.io/content-management/syntax-highlighting/#highlighting-in-code-fences

**Comment by Lednerb** [comment]
This hugo theme actually does not use the built-in code highlighting but the `highlight.js` library.

It should be evaluated if the built-in functions will be a better fit nowadays.

**Comment by igor-baiborodine** [comment]
The line numbers feature is not implemented in `highlight.js`:
https://highlightjs.readthedocs.io/en/latest/line-numbers.html

**Comment by igor-baiborodine** [comment]
Regarding this issue, I created a new discussion in the **Ideas** category: https://github.com/Lednerb/bilberry-hugo-theme/discussions/362
