### ISSUE TITLE
video shortcut (type="youtube") doesn't load video

### ISSUE THREAD

**Issue by darrenaddy** [Lednerb/bilberry-hugo-theme#365]
Can someone tell me if I am doing something wrong or if there is an issue here?

The README.md says:
`The second option is to use the video shortcode within markdown content in a post of the **article** type as follows:

{{< video type="youtube" id="<youtube-video-id>" >}}
`

SO, to try this, I create a new article using:
`hugo new content/article/my-article-with-video.md`

It looks like this:
`---

title: "Coffee Kombucha Equals Koffucha!"
date: 2022-03-08T10:24:06-06:00
draft: false

categories: ['coffee']
tags: ['fermentation' , 'kombucha']
toc: false
author: "Darren Addy"
---

{{< video type="youtube" id="OweuMTg1nbQ" >}}

Lorem ipsum blah blah
`
Everything works perfectly when I save, except no video shows. Instead I get this (note: I do NOT have javascript disabled):

The YouTube player can not be loaded with disabled JavaScript. The following video is embedded here: https://youtube.com/watch?v=OweuMTg1nbQ Lorem ipsum blah blah

**Comment by igor-baiborodine** [comment]
@darrenaddy, do you test it in your local dev? To set up your website, did you use the Quick Start guide from the README documentation?

**Comment by darrenaddy** [comment]
Yes, I used the Quick Start guide from the README to set up.
If by testing "in your local dev" you mean starting the server and running it in localhost:1313 - then yes. That is what I'm trying to get to work. The content type "video" is working fine for YouTube videos.

The shortcode for video in the **article** content type is what is not working.

I am just trying to learn **Hugo as a SSG** before I learn any more tangentally related stuff like GIT, Github, Netlify, CMS, Tailwind CSS, or any of the other crap that people try to corral into Hugo. I just want to learn HUGO with a theme that looks like it makes sense. I don't install themes via git. I download the code, extract it, put it in my Hugo site's themes folder and copy the ExampleSite contents over in to the Hugo site's root content folder (and edit the config.toml and start the local server). Bilberry looks like it makes sense, but **this** is not working according to how the documentation says it should. All of the info is in my post (except I don't know how to show the code of a Hugo .md file properly because it changes the formatting and turns the closing three dashes of the front matter into an HR tag.

**Comment by igor-baiborodine** [comment]
@darrenaddy, May I ask you to clone the Bilberry Sandbox repository into your local dev and start it with the `hugo server` command?
```shell
git clone https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox.git
cd bilberry-hugo-theme-sandbox
hugo server
```

Then check if the following article with the YouTube video is displayed correctly: http://localhost:1313/article/test-youtube-video-in-article-post/

It should be displayed as follows: https://www.bilberry-sandbox.kiroule.com/article/test-youtube-video-in-article-post/

**Comment by igor-baiborodine** [comment]
@darrenaddy, please provide a sequence of steps to reproduce it in my local dev. Otherwise, I will close this issue.
