### ISSUE TITLE
Responsive layout is not ideal

### ISSUE THREAD

**Issue by h0gan1ee** [Lednerb/bilberry-hugo-theme#372]
We've forked the theme and fix the problem. Maybe you can use our solution.

The forked theme: https://github.com/hitszlug/bilberry-hugo-theme

This site uses the forked theme: https://weekly.hitsz.org

For comparison:
![IMG_20220314_000336.jpg](https://user-images.githubusercontent.com/39949564/158068382-2fd94663-14a9-4444-a10f-4841c61590bf.jpg)
![IMG_20220314_000428.jpg](https://user-images.githubusercontent.com/39949564/158068384-e945bb53-f6a7-447a-b61c-e5f1dc471011.jpg)

**Comment by h0gan1ee** [comment]
## Problems

### Header

- Not enough padding.
- Buttons are too close to text.
- Text and icon are too big and not vertically aligned.

### Footer

- Not horizontally aligned.
- Gutters are too small.
- Padding is inconsistent.

### Article

- Card view should be replaced. Otherwise it should have enough margin.

### Navigation Bar (Column)

- Not enough padding.

**Comment by igor-baiborodine** [comment]
@h0gan1ee, let me check the changes you made in your fork and see if we can incorporate them.

**Comment by igor-baiborodine** [comment]
I did my best to filter out all the relevant commits in your fork. Therefore, closing this issue.
