### ISSUE TITLE
Colours in use are inconsistent to theme colours

### ISSUE THREAD

**Issue by h0gan1ee** [Lednerb/bilberry-hugo-theme#373]
While modifying the style sheets of this theme to derive a new theme, I found many unnecessary explicitly defined colours.

I am sorry that I couldn't point out all of them, but you might take a look at our forked theme (https://github.com/hitszlug/bilberry-hugo-theme), which addressed most of the problems.

**Comment by igor-baiborodine** [comment]
I did my best to filter out all the relevant commits in your fork. Therefore, closing this issue.
