### ISSUE TITLE
Dead SCSS code found

### ISSUE THREAD

**Issue by h0gan1ee** [Lednerb/bilberry-hugo-theme#374]
Again, when I messing around with the theme, I found various dead style declaration which has no effects.

I didn't make a list of them, but they should be reflected on the commits of [our forked theme](https://github.com/hitszlug/bilberry-hugo-theme).

**Comment by RoneoOrg** [comment]
Hi @h0gan1ee and thanks for the tip.
The [comparison](https://github.com/Lednerb/bilberry-hugo-theme/compare/master...hitszlug:master) shows a lot of noise though, did you use a code formater?

**Comment by igor-baiborodine** [comment]
I did my best to filter out all the relevant commits in your fork. Therefore, closing this issue.
