### ISSUE TITLE
Featured Image: Size and Alt-Attribute

### ISSUE THREAD

**Issue by rabarar** [Lednerb/bilberry-hugo-theme#44]
it would be nice to add parameters to the `featuredImage` so that the size could be established rather than expand the image to the full-size of the article div container (and it might be nice to add an alt parameter too if you add width and height).

**Comment by Lednerb** [comment]
How would you use this?

I mean, for example, if you use an image in portrait mode, etc. ?
Then it would not fill out the full width of the post container but be centered?
Can you provide me a screenshot or a scribble for a better understanding?

In my opinion, these parameters would complicate the cool ease-of-use and won't be used by the majority of the users.

------
However, the `alt` attribute is nice, and I think I will set it to the post's title per default?

**Comment by rabarar** [comment]
take a look at this link https://cyberspy.io/code/gogo/ - notices how big the image is when the actual image is much smaller and is being resized to the width of the container. Rather than blow it out, centering it at the original size would look better IMHO

**Comment by cripplet** [comment]
Re. image resize -- this seems like a JS / CSS trick, not necessarily an issue of layout (by using JS to query the image size and setting max-width / height on the image element).

@rabarar re. alt-text, that seems like a simple change that would be easy to create a PR for -- you'll need to alter https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/featured-image.html to add the alt image attribute.

**Comment by Lednerb** [comment]
In the next days, I will have more time to work on the open issues and implement the `alt` attribute.

At the moment I think the resizing as @cripplet can be implemented but I would prefer that the users create an image for the max-width so the article is covered by a high-quality image (also think about the HDPI-screen and/or retina display users).

If you invest your time in an article, it's featured image should look nice, too ;)

**Comment by rabarar** [comment]
Setting the image width and height didn't work for me when I modified the layout to do so. It only resampled the smaller image

**Comment by Lednerb** [comment]
@rabarar The resizing to the full-width would always result in a low quality and stretched image.

The best way IMHO is to create a `700px`-width image that matches your expectations. 

(Create the image, in your example, maybe a 700x100 px white-image and place the Gopher icon in the center, save it and use it for your article.)
