### ISSUE TITLE
Linked Image

### ISSUE THREAD

**Issue by Brazier85** [Lednerb/bilberry-hugo-theme#457]
### Discussed in https://github.com/Lednerb/bilberry-hugo-theme/discussions/456

<div type='discussions-op-text'>

<sup>Originally posted by **Brazier85** December  5, 2022</sup>
Hello,

I would like to use a linked image on my page. 

But the combination of markdown link an image is not working properly.
`[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/LyErffRX0HM/0.jpg)](http://www.youtube.com/watch?v=LyErffRX0HM)`

It renders like this:
![image](https://user-images.githubusercontent.com/1213924/205659735-ee538196-0937-43f9-ba7d-f985decf61dc.png)

Does someone know how I can fix this?
</div>

**Comment by igor-baiborodine** [comment]
@Brazier85, fixed with commit https://github.com/Lednerb/bilberry-hugo-theme/commit/bd6ef8565583713cd64e30a86670fd1358c77977.

**Comment by Brazier85** [comment]
> @Brazier85, fixed with commit https://github.com/Lednerb/bilberry-hugo-theme/commit/bd6ef8565583713cd64e30a86670fd1358c77977.

Awesome. Thank you! I'll try it tomorrow
