### ISSUE TITLE
Bilberry seems to ignore thumbnail in generating og:image 

### ISSUE THREAD

**Issue by ginabythebay** [Lednerb/bilberry-hugo-theme#459]
I'd like a more control over the image preview of my pages in the open graph protocol.  Currently I have an article with a featured image and when I post a link to the article in mastodon, the image preview is just a brown blur.  I'm guessing it is taking the entire featured image and then guessing, badly, which part to crop down to size.

I tried creating a thumbnail.jpg, per these instructions https://www.hackification.io/software-development/hugo/html/open-graph-tags/ but it was ignored.

It appears that bilberry/layouts/_default/baseof.html does its own thing and there is no allowance for thumbnails.  Does anyone of advice for how I could best work around this, or perhaps modify bilberry in a way that makes sense to support thumbnails?

**Comment by igor-baiborodine** [comment]
I will modify the `baseof.html` partial to include the `opengraph.html` partial as suggested in the Hugo documentation for the [Open Graph metadata](https://gohugo.io/templates/internal/#configure-open-graph). It will be available in the next release.

**Comment by igor-baiborodine** [comment]
Fixed with commit https://github.com/Lednerb/bilberry-hugo-theme/commit/0971422110920f48f6f4bb6207ef878eccfa4177. Please see the [Open Graph Metadata](https://github.com/Lednerb/bilberry-hugo-theme#open-graph-metadata) section in `README`.
