### ISSUE TITLE
Error copying static files : permission denied

### ISSUE THREAD

**Issue by KHannibal** [Lednerb/bilberry-hugo-theme#464]
Hey,

With Bilberry 3.16.0, I can't build the site anymore because of the error below. Removing or adding arguments to the `hugo` command does not change the behavior. My second website is using [Geekdoc](https://github.com/thegeeklab/hugo-geekdoc) and builds without issue.

`cd /Users/~/Sites/blog && hugo --cleanDestinationDir --forceSyncStatic --ignoreCache --minify --gc`
`hugo: downloading modules …`
`go: downloading github.com/Lednerb/bilberry-hugo-theme/v3 v3.16.0`
`go: downloading github.com/Lednerb/bilberry-hugo-theme v1.0.1`
`hugo: collected modules in 555 ms`
`Start building sites … `
`hugo v0.108.0+extended darwin/arm64 BuildDate=unknown`
`Error: Error copying static files: open /Users/~/Sites/blog/public/theme.js: permission denied`
`Total in 798 ms`

I'm running hugo (latest version), installed via Homebrew (latest version) on macOS 13.1.

**Comment by igor-baiborodine** [comment]
@KHannibal, please delete manually the `/Users/~/Sites/blog/public` folder and execute the build command: `hugo --cleanDestinationDir --forceSyncStatic --ignoreCache --minify --gc`.

**Comment by KHannibal** [comment]
It is working now (I wonder why I didn't think of your fix by myself), thank you ! 👍 

(Now I've other issues linked to the opengraph thing, but I'll investigate further because it looks like hugo is to blame and not your theme.)
