### ISSUE TITLE
Categories links at the bottom panel are broken

### ISSUE THREAD

**Issue by hakerdefo** [Lednerb/bilberry-hugo-theme#476]
In the demo website [https://lednerb.github.io/bilberry-hugo-theme/](https://lednerb.github.io/bilberry-hugo-theme/), at the bottom panel, `CATEGORIES` links are completely broken and error out in GitHub pages 404 page. For example `CATEGORIES` at the bottom panel links to following broken link,

[https://lednerb.github.io/categories/](https://lednerb.github.io/categories/)

And, `Music` under the `CATEGORIES` links to this dead link,

[https://lednerb.github.io/categories/music](https://lednerb.github.io/categories/music)

And,` Privacy`  under the `CATEGORIES `links leads to this invalid link,

[https://lednerb.github.io/categories/privacy](https://lednerb.github.io/categories/privacy)

Great theme BTW :+1:

**Comment by igor-baiborodine** [comment]
Fixed with [v3.19.0](https://github.com/Lednerb/bilberry-hugo-theme/releases/tag/v3.19.0) release.
