### ISSUE TITLE
Front Matter Summary Split - Continue reading link not appearing

### ISSUE THREAD

**Issue by darren-johnson** [Lednerb/bilberry-hugo-theme#499]
Hi there,

As per the README.md 

"Front Matter Summary Split
To define a summary that differs from the text that starts your article, use the summary front matter variable, for example, summary: "Here goes my summary". This summary will also be followed by the Continue reading link"

When I add summary front matter the continue reading link does not appear as suggested.

**Comment by igor-baiborodine** [comment]
@darren-johnson, fixed in [v3.22.0](https://github.com/Lednerb/bilberry-hugo-theme/releases/tag/v3.22.0).
