### ISSUE TITLE
Wrong language code in filename

### ISSUE THREAD

**Issue by aerohub** [Lednerb/bilberry-hugo-theme#50]
Hello, @Lednerb ! There is a wrong language code in use: https://github.com/Lednerb/bilberry-hugo-theme/blob/master/i18n/uk.yaml

**UK** is an abbreviation for United Kingdom
**UA** is a language code for Ukrainian

Cheers

**Comment by aerohub** [comment]
I am sorry, @Lednerb , I am wrong. **UK** is right code.

**Comment by Lednerb** [comment]
Hi @aerohub, yeah my girlfriend and I were also surprised and had to search for it on the internet...
