### ISSUE TITLE
Add Reading Time to content header

### ISSUE THREAD

**Issue by rabarar** [Lednerb/bilberry-hugo-theme#51]
Modify `layout/partials/default-content` adding 
```
<span class="categories">
            {{ .ReadingTime }}
            {{ with .Site.Data.l10n.articles.readingtime }}{{.}}{{end}}
</span>
```

adding the reading time inline with the article date, categories, author line...

**Comment by Lednerb** [comment]
Implemented it. Next release will have a config option to enable or disable the reading time output.
