### ISSUE TITLE
Custom theme not recognized while deploying

### ISSUE THREAD

**Issue by bellons91** [Lednerb/bilberry-hugo-theme#527]
Hello.
I'm trying to customize colors and style of this theme.

I followed these steps:

1. Copy the whole bilberry-hugo-theme folder within the \themes folder of my blog, as described in the documentation;  ![image](https://user-images.githubusercontent.com/6106586/229589497-1e7e191d-0c57-4a00-9c43-68db68b54021.png)
2. uncomment `theme = "bilberry-hugo-theme"` in config.toml
3. change variable value
4. run `npm install`
5. run `npm run dev`. I see this message: 
![image](https://user-images.githubusercontent.com/6106586/229590465-27467b13-c114-4635-a31b-87a92f9fdb2b.png)
6. run `hugo server`

Everything works well correctly.
 
But, when it comes to deploying on Netlify, I receive this error:

> Failed during stage 'preparing repo': Error checking out submodules: : fatal: No url found for submodule path 'themes/bilberry-hugo-theme' in .gitmodules

I suppose this is because, when copying the theme withing my _themes_ folder, I also bring info about the source Git repository.

What is the expected behavior? 

Should I push both my blog and the customized theme? Or maybe, running `npm run production` should generate some files that are the only ones I have to include in my commits? Another option is to remove any reference to Git on the _themes_ folder and include everything in my repository.

**Comment by igor-baiborodine** [comment]
@bellons91, could you please point me to the GitHub repository which you are trying to deploy on Netlify?

**Comment by igor-baiborodine** [comment]
Also, the `resources/_gen/images` and `.hugo_build.lock` should not be committed.

**Comment by igor-baiborodine** [comment]
Resolved. See this thread for more details: https://github.com/code4it-dev/c4it-hugo/pull/4
