### ISSUE TITLE
Theme does not respect date format strings

### ISSUE THREAD

**Issue by cripplet** [Lednerb/bilberry-hugo-theme#53]
Per, https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/default-content.html#L4, post date formats should be YYYY-MM-DD; however, we see in the preview / demo, actual format differs; refreshing really fast looks like the date is altered after loading -- perhaps in JS or CSS.

Is this intended behavior?

![capture](https://user-images.githubusercontent.com/3048682/34070576-3ffbf996-e21d-11e7-9d34-dbdfbdd8124c.PNG)

**Comment by cripplet** [comment]
Looks like https://github.com/Lednerb/bilberry-hugo-theme/blob/ec54f18c630bc2c6a430c858ebf94f9b886a59ff/layouts/_default/baseof.html#L46 is responsible. Maybe this should be an optional thing instead?

**Comment by Lednerb** [comment]
Hey @cripplet and thank you for your contributions!

It was my intention to have the date always translated into the actual language.
The `moment` library changes the date according to the language-format (_November 1, 2017_ for English, _1. November 2017_ in German for example).

Maybe we can add a config variable for `enable_date_translation` or something like this to disable this behavior if the users want to.

It's always a trade-off for the theme between easy to use and highly customizable...

**Comment by cripplet** [comment]
My particular issue with this was that you could see the flicker between loading and render, which is sort of irksome -- I would personally prefer this being pre-rendered during the compilation step.

I wonder if it's possible to leverage just https://gohugo.io/functions/format/, based on a language switch. It looks like Hugo doesn't support auto-localization formatting yet -- were you looking to translate the dates into e.g. German as well, or keeping the English month names?

**Comment by Lednerb** [comment]
Yeah, the flicking is a problem...
Maybe we can prevent this behavior by loading the `moment.js` library earlier...

At the moment Hugo has no built-in support for different languages (Month names).
I've decided to use `moment.js` to avoid the effort for updating and translating the month names for every language and have a large if-else switch for the date formats.

I'm open to any tips and solutions for this issue.

**Comment by Lednerb** [comment]
I will implement configuration options to customize the date output.

**Comment by Lednerb** [comment]
Hi @cripplet 

I've implemented further configuration options that will be shipped with the next release.

Thanks for your input.
