### ISSUE TITLE
OGP does not work

### ISSUE THREAD

**Issue by atsuyaw** [Lednerb/bilberry-hugo-theme#538]
I want to set an image for the social preview independently of the avatar setting for the header.
I am not sure that this theme has such a function; anyway, I could not have set any image correctly.
I've attempted some patterns, but the behavior seems strange.

I guess the following issues bring this problem:
1. The hash value for gravatar is not generated correctly.
1. The image which is set for the avatar (without gravatar) is not applied for the preview outside of the `gallery` category.

I set up the avatar in the [`config.toml`](https://github.com/atsuyaw/atsuyaw.github.io/blob/main/config.toml) to display the image in blog cards or Twitter/Facebook card via OGP:
```TOML
[params]
    avatarEmail = "watanabe@osakafu-u.net"
    customImage = "https://atsuyaw.github.io/images/avatar.jpg"
```
however, it does not work as I expected.
This is a result obtained by the debugger tool of Facebook:
| ![image](https://user-images.githubusercontent.com/68371029/233935290-1fa4d407-0b91-49f7-b1ca-308d12a853be.png)|
|:--|

The avatar is not applied for the link preview.
Checking the value of `og:image` the debugger obtain,  it can be seen that the value is not correct.
> https://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?size=200

The actual HASH can be obtained at my gravater page: http://gravatar.com/atsuyaw
and it is `106020ae5e86580ce4a8f90df1e41b4c`.

Further, only in the case of [the index page of `gallery`](https://atsuyaw.github.io/gallery/), the `customImage` is applied for the preview.
| ![image](https://user-images.githubusercontent.com/68371029/233939538-6a6ed672-4d88-4a6e-95e2-55fa6c2b42e6.png)|
|:--|

This may be expected behavior.
Thus, the function setting the avatar for the preview seems working correctly in the `gallery` category.

Furthermore, I recommend adding the declaration for OGP to the header; Please consider!
#537

**Comment by igor-baiborodine** [comment]
@atsuyaw, let me investigate it.

**Comment by Sp-cy** [comment]
I went to investigate this myself after noticing that the OG social share image of my site was also broken even after specifying in the config file the archive from the static folder that had to be used.  In my case my config was like this:
`images = "ChromaPortraitCrop.webp"` 
and I decided to try to change it for this:
`images = ["ChromaPortraitCrop.webp"]`
Which corrected the issue, not sure if entirely, the image is tiny, but it's fine. 

![Screenshot showing a website link being shared in a chat, one displaying an OG image and the other not displaying it](https://user-images.githubusercontent.com/68587155/234505091-d6cce44d-dc9d-47df-b078-5c04bc4ced9d.png)

**Comment by igor-baiborodine** [comment]
Fixed with PR https://github.com/Lednerb/bilberry-hugo-theme/pull/537
