### ISSUE TITLE
Config Logo RollOver

### ISSUE THREAD

**Issue by davideriboli** [Lednerb/bilberry-hugo-theme#56]
Hi Sascha,

I've found the config param to set the logo to a gravatar or a custom image, but I can't find a way to change the green home icon that appears on rollover. 

Can you point me in the right direction?

I think it could be useful to have a param in config to set the rollover image and another one to set rollover Yes/No.

**Comment by Lednerb** [comment]
Hi Davide,

at the moment the hover icon is hard-coded here: https://github.com/Lednerb/bilberry-hugo-theme/blob/master/layouts/partials/header.html#L11

You can change the overlay icon with any other [Font Awesome icon](http://fontawesome.io/icons/) by changing the class of the `<i>` element or put your custom icon / image, etc. in the `<span>` element.

I will think about an option to implement a custom hover icon or image.

**Comment by Lednerb** [comment]
Now possible via hugo pipelines and an optimized scss variables file. Maybe configurable via the main `config.toml` file.

Working on it...

**Comment by Lednerb** [comment]
Hi @davideriboli,

I've implemented a config option to switch the default overlayIcon.

Check out the next release for the changes :)
