### ISSUE TITLE
v4: modal zoom with MagnificPopup not working

### ISSUE THREAD

**Issue by igor-baiborodine** [Lednerb/bilberry-hugo-theme#561]
The modal zoom for images is no longer working in the `v4` version. Clicking on the image gives the following error:

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/a1c9ecfc-3332-4d71-97b7-aed6101304d6)

The event passed into the `disableOn` function is undefined:

https://igor-baiborodine.github.io/bilberry-hugo-theme-sandbox/article/test-image-modal-zoom/

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/4e0fdaf9-2875-48b6-b6df-4f9a631d1907)

In the `v3` version, the event is defined:

https://www.bilberry-sandbox.kiroule.com/article/test-image-modal-zoom/

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/8c62200b-0968-434f-a603-f68c7d11893e)

In `v4` version, the `theme.js` asset is created using the Hugo pipes in the [js.html](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/v4/layouts/partials/js.html) partial. For some reason, this `theme.js` does not work the same in regards to the modal zoom feature.

@Lednerb, @Sp-cy I tried to debug this issue, but I'm not able to pinpoint the cause. Web development with JavaScript is not my forte. If you have time, could you please look into this issue? That's the only issue I have with the new `v4` version, and it's blocking from releasing the `v4`.

**Comment by Lednerb** [comment]
Hi @igor-baiborodine 

at the moment I'm totally out of time so I can not get into it.

As a quick "workaround":
Maybe it's easier to implement another modal zoom function via plugin or plain js? 
If the behavior is the same, it should not make a huge difference for the users.

**Comment by igor-baiborodine** [comment]
@Lednerb, thanks for the tip. I will look into an alternative to the Magnific Popup.

**Comment by Sp-cy** [comment]
I don't know JS. I took a look and my brain just kept saying Jquery. I'm sorry I can't be of any help this time.
