### ISSUE TITLE
Testing error in exampleSite

### ISSUE THREAD

**Issue by atsuyaw** [Lednerb/bilberry-hugo-theme#594]
Currently, the `hugo server` doesn't work in `v4/exampleSite` and `v4/tests/exampleSite` with the following error:
> WARN  config: languages.de.subtitle: custom params on the language top level is deprecated and will be removed in a future release. Put the value below [languages.de.params]. See https://gohugo.io/content-management/multilingual/#changes-in-hugo-01120

I think it's better to delete the following lines.

https://github.com/Lednerb/bilberry-hugo-theme/blob/e35ecca9f03c9579a9fca7aba0b5aa01563f197c/v4/exampleSite/config.toml#L172

https://github.com/Lednerb/bilberry-hugo-theme/blob/e35ecca9f03c9579a9fca7aba0b5aa01563f197c/v4/tests/exampleSite/config.toml#L145

**Comment by atsuyaw** [comment]
Oh sorry, the major reason for not workin hugo was my fault!: 
> Error: failed to load modules: module "bilberry-hugo-theme/v4" not found in "/home/atsuyaw/Documents/bilberry-hugo-theme/v4/tests/exampleSite/themes/bilberry-hugo-theme/v4"; either add it as a Hugo Module or store it in "/home/atsuyaw/Documents/bilberry-hugo-theme/v4/tests/exampleSite/themes".: module does not exist

but anyway, it should be considered in the future i guess

**Comment by igor-baiborodine** [comment]
@atsuyaw, currently, the minimally supported version of Hugo for the theme is `v0.109.0`. The raised warnings come when the Hugo version is `v0.112.0` or higher. Therefore, the config file in the example site will be adjusted when the minimally supported version is upgraded to `v0.112.0` or higher.

**Comment by atsuyaw** [comment]
i got it, thanks!
