### ISSUE TITLE
Linked images seems do not work

### ISSUE THREAD

**Issue by eosfor** [Lednerb/bilberry-hugo-theme#599]
Things like this do not work for some reason. They reference the badge picture. Meaning it shows the badge, but the link also leads to the badge not to the external site

```
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/eosfor/scripting-notes/HEAD)
```

**Comment by igor-baiborodine** [comment]
@eosfor, it's fixed in [v4.1.0](https://github.com/Lednerb/bilberry-hugo-theme/releases/tag/v4.1.0).

Please use the `hyperlink-image` shortcode; see the ["Hyperlink Image"](https://github.com/Lednerb/bilberry-hugo-theme#hyperlink-image) section in README.

Test article:
- https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/blob/master/content/article/test-image-as-hyperlink.md
- https://www.bilberry-sandbox.kiroule.com/article/test-image-as-hyperlink/

**Comment by Sp-cy** [comment]
This is a great feature addition! Thank you!

**Comment by eosfor** [comment]
Great, thanks. Quick question though, when i use it this way

```
> If you want to try this out, there is a Jupyter notebook, which works in {{< hyperlink-image "Binder" "https://mybinder.org/badge_logo.svg" "https://mybinder.org/v2/gh/eosfor/scripting-notes/HEAD" >}}
```

It puts the badge into the center of the note, which does not look good IMHO. Can I do smth with it?

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/9363027/5fa0808e-499c-4ecf-8ae4-d0e6949e2d91)

And the last but not least :), is there a way to make these notes of a different color, say yellow-ish, red-ish, just to help put some emphasis here and there? 

Thanks :)

**Comment by Sp-cy** [comment]
You can modify all this yourself either by following the [Colors and Fonts](https://github.com/Lednerb/bilberry-hugo-theme#colors-and-fonts) instructions in the Read Me or modifying the theme's scss files in v4/assets/scss. You could copy all the files from the theme's folder to your own sites assets folder before making any changes so they stay even after upgrading the theme's version.

**Comment by igor-baiborodine** [comment]
> And the last but not least :), is there a way to make these notes of a different color, say yellow-ish, red-ish, just to help put some emphasis here and there? 

@eosfor, to customize the look and feel for these elements, you can implement a custom CSS file and integrate it as described in the ["CSS and JS modules"](https://github.com/Lednerb/bilberry-hugo-theme/blob/master/v4/README.md#css-and-js-modules) section of README.
