### ISSUE TITLE
Article, gallery, video... not generated

### ISSUE THREAD

**Issue by indmind** [Lednerb/bilberry-hugo-theme#61]
Hi, I am new to Hugo, when I run using `hugo server -D` it works perfectly, but if I generate using `hugo -t bilberry-hugo-theme`  command,  articles are not showing up. <https://indmind.github.io/blog/>.
source code: https://github.com/indmind/blog
 thanks

**Comment by Lednerb** [comment]
Hey @indmind 

it seems in your source code that you have the `draft: true` flag active.

`hugo server -D` spins up a local server and the `-D` flag is for rendering the drafts. Just delete the `draft: true` lines (or change them to `draft: false`) in the content files and run `hugo` to generate the `public` folder with every site rendered in a ready to upload version.

**Comment by indmind** [comment]
oh, thanks. after removing all `draft: true` it works!
