### ISSUE TITLE
When I serve the site, I get the "Page Not Found" error.

### ISSUE THREAD

**Issue by ziyaorhan** [Lednerb/bilberry-hugo-theme#614]
Hello, this is my first time installing a hugo-go theme locally. When I follow the [instructions ](https://themes.gohugo.io/themes/bilberry-hugo-theme/#site-initial-setup)and serve the site, I get the "Page Not Found" error.

- my hugo version : v0.121.0
- my go version : go1.21.3 windows/amd64

Warnings I received from `hugo server` :

WARN  found no layout file for "html" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "home": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "section": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN  found no layout file for "html" for kind "term": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.

**Comment by igor-baiborodine** [comment]
@ziyaorhan, make sure you installed the extended version of Hugo. Also, which theme installation option have you used?

**Comment by ziyaorhan** [comment]
@igor-baiborodine, yes it looks "extended": hugo v0.121.0-e321...+extended windows/amd64.
I tried the second and third options.

**Comment by igor-baiborodine** [comment]
@ziyaorhan, it's hard to say what went wrong. If you push your site code to a GitHub repo, I will investigate your issue in my local dev.

**Comment by ziyaorhan** [comment]
@igor-baiborodine, you can access the [codes](https://github.com/ziyaorhan/test-for-hugo-go.git).

**Comment by igor-baiborodine** [comment]
@ziyaorhan, remove the `hugo.toml` file in your repository. You cannot have `config.toml` and `hugo.toml` at the same time.

**Comment by ziyaorhan** [comment]
@igor-baiborodine, I'm new to Hugo and didn't realize this. Yes, the problem was solved when I removed the` hugo.toml` file. Thank you for taking the time to review my codes.
