### ISSUE TITLE
Algolia add record: too big

### ISSUE THREAD

**Issue by lebarde** [Lednerb/bilberry-hugo-theme#62]
Hello,
Thank you for this very good theme!

I am using it on [garamond.fr](http://garamond.fr). I posted a short story (1900 words). Algolia claims for a too big record.

What could I do? Maybe we should cut the json record?

Thank you by advance.

**Comment by Lednerb** [comment]
Hi @lebarde 
please excuse me for my late reply...

Nice website!
I've found this FAQ: https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records/

So maybe we can modify the json so not the whole article but only the first 300 or 500 words are used?

**Comment by Lednerb** [comment]
For the moment I will remove the `content` complete because it does not make much sense to search through novels or tutorials itself.

For searching, there is the author, the title, the tags and the categories. This solution should be convenient and effective.
