### ISSUE TITLE
Error in documentation (readme): Wrong path for customized 404

### ISSUE THREAD

**Issue by LoSong** [Lednerb/bilberry-hugo-theme#629]
It reads:

> 404 Page
> To customize your 404 page, copy the themes/bilberry-hugo-theme/layouts/404.html file to your site's **layouts/404.html** and edit the file according to your needs, for example, change the message, icon class etc.`

It must read:

> 404 Page
> To customize your 404 page, copy the themes/bilberry-hugo-theme/layouts/404.html file to your site's **static/404.html** and edit the file according to your needs, for example, change the message, icon class etc.`

**Comment by igor-baiborodine** [comment]
@LoSong, the HTML template shouldn't be copied to the `static` folder. Here is an example for www.kiroule.com:
1. https://github.com/igor-baiborodine/kiroule.com/blob/master/layouts/404.html
2. https://www.kiroule.com/non-existing-page
