### ISSUE TITLE
Does this theme supports Google Analytics?

### ISSUE THREAD

**Issue by thieunv90** [Lednerb/bilberry-hugo-theme#63]
I've just taken a look at this theme, this is awesome and I wanna use it. But I have a question, does this theme supports Google Analytics or not?

**Comment by Lednerb** [comment]
Hi,

the theme supports google analytics.
Just add your tracking id here in your site's `config.toml`:
https://github.com/Lednerb/bilberry-hugo-theme/blob/master/exampleSite/config.toml#L10-L11


Google Analytics is supported by hugo as a default, so the theme doesn't change anything on the original hugo implementation:
https://gohugo.io/templates/internal/#google-analytics
