### ISSUE TITLE
about topnav

### ISSUE THREAD

**Issue by Suremotoo** [Lednerb/bilberry-hugo-theme#64]
i can't change the topnav ? please help me .☹️

**Comment by Lednerb** [comment]
What's the problem? You can adjust the visibility via the theme's config file.
To add or remove the menu items adjust the `page` post types contents:

https://github.com/Lednerb/bilberry-hugo-theme#pages-and-external-links

**Comment by Suremotoo** [comment]
OK. got it ! thanks!
i love this theme , just like you.😅😉
