### ISSUE TITLE
Google Analytics configuration has new syntax

### ISSUE THREAD

**Issue by rserbitar** [Lednerb/bilberry-hugo-theme#649]
Total noob here, so maybe I am doing something wrong, but thats what I had to do:

Configuration in hugo.toml

Before:

`googleAnalytics = 'G-MEASUREMENT-ID'`

working:

```
[services]
  [services.googleAnalytics]
    ID = 'G-MEASUREMENT_ID'

```

**Comment by igor-baiborodine** [comment]
Fixed with https://github.com/Lednerb/bilberry-hugo-theme/releases/tag/v.4.7.0 release.
