### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by boydkelly** [Lednerb/bilberry-hugo-theme#77]
Nice theme!
Sorry for the newbie questions.  But I'm looking for a simple multilingual site with 2 or 3 pages, but not at least for now will not be a blog. 

I can't see how to get the/a language selector to appear either in the header or footer.

Will it be possible to get a home landing page that does not contain 'blog posts'?  And then in time have a menu item to go to the "blog"?

Is it possible to make a page type that has no discus commenting permitted?

**Comment by Lednerb** [comment]
Hi @boydkelly 

> Sorry for the newbie questions. But I'm looking for a simple multilingual site with 2 or 3 pages, but not at least for now will not be a blog.

The multi-language version will be published in the next days. See #48 for more information.
There is also a language chooser implemented, but not published in the `master` branch yet.

> Will it be possible to get a home landing page that does not contain 'blog posts'? And then in time have a menu item to go to the "blog"?

A special landing page is not planned at the moment. However you could set up a server redirect to a specific `page` post type that's acts like your landing page (for example an about page: https://lednerb.github.io/bilberry-hugo-theme/page/about-bilberry/)

With the option to show always the top navigation you can add a `link` post type that returns you to your `blog` section and so on.

That's not really the intended use case but maybe you can archive your goal this way.

> Is it possible to make a page type that has no discus commenting permitted?
Sure, maybe we can add an option for disabling the commenting function as `disableComments: true` but at the moment it's not implemented yet.

You can open a feature request issue for this or send a PR ;)
