### ISSUE TITLE
Feature request simple page with no commenting 

### ISSUE THREAD

**Issue by boydkelly** [Lednerb/bilberry-hugo-theme#78]
I believe a win-win for bilbery theme would be to include a page type/layout (sorry i'm new so excuse any terminology errors!) that would display a page with no discus comment options, no date, and not include the categories and tags from the page bottom.  (The social links could stay) This could allow bilbery theme the flexibility to use for a small business or organization that does not use a blog.  BUT it would also easily allow adding a future blog on the site, or allow a small business to have a 3 page static service site and an identically styled  blog site.

**Comment by Lednerb** [comment]
Implemented all features here.

Everything is optional and there is even a `showFooter` option since 538afc9

You can even decide which columns in the footer you want to use.

**Comment by boydkelly** [comment]
awesome!
