### ISSUE TITLE
Space problem on main menu

### ISSUE THREAD

**Issue by boydkelly** [Lednerb/bilberry-hugo-theme#80]
Thanks for great theme.  I am using the multiLang branch for the time being and I really like the language switcher on the top navbar.

Just one issue/request:  I have disabled the search feature, but my four menu items in French wrap on the left side even though there is more than sufficient space across the nav bar without search.  Can the space available for menu items be increased when the search feature is disabled?  Thanks!

**Comment by Lednerb** [comment]
Related to #48
