### ISSUE TITLE
Current fonts is not supported for Unicode character

### ISSUE THREAD

**Issue by anhchungite** [Lednerb/bilberry-hugo-theme#93]
Use of **Lato** fonts and **Raleway** is not supported for some Unicode characters.
![capture](https://user-images.githubusercontent.com/28822504/41648193-701f37ce-74a2-11e8-9277-a3463acfb63d.PNG)
I propose using a font that supports Unicode characters such as **Open Sans** or **Roboto**.
https://fonts.google.com/specimen/Open+Sans
https://fonts.google.com/specimen/Roboto

I know that it is possible to edit it in scss, but this is my opinion, please consider.

**Comment by Lednerb** [comment]
Closed by de09643
